# Generated by Django 3.2.8 on 2021-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='mod_pc',
            field=models.IntegerField(),
        ),
    ]
