# Generated by Django 3.2.8 on 2021-10-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_tenant_mod_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='co',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='dist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='house',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='lm',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='loc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='pc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='po',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='street',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='subdist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='vtc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_req_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.landlord'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_co',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_dist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_house',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_lm',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_loc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_pc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_po',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_street',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_subdist',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mod_vtc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='request_code',
            field=models.IntegerField(null=True),
        ),
    ]
