# Generated by Django 3.2.8 on 2021-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20211030_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='token',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='token',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
