# Generated by Django 3.2.8 on 2021-10-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20211030_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
