# Generated by Django 3.2.8 on 2021-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20211031_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_req_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='request_code',
        ),
        migrations.AddField(
            model_name='tenant',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
