# Generated by Django 3.2.8 on 2021-10-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20211031_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='mod_country',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_dist',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_lm',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_loc',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_pc',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_po',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_state',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_street',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_subdist',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mod_vtc',
        ),
    ]
