# Generated by Django 3.2.8 on 2021-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20211031_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='reqCode',
            field=models.IntegerField(null=True),
        ),
    ]
