# Generated by Django 3.2.8 on 2021-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tenant_reqcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='aadharnum',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='aadharnum',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
