# Generated by Django 3.2.8 on 2021-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20211031_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='reqCode',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
