# Generated by Django 3.2.8 on 2021-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_tenant_reqcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=5000, null=True)),
                ('initiator', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
